<a href="https://colab.research.google.com/github/AmanYadavKHD/PytorchCampusX/blob/main/Vid2_tensors_in_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
print(torch.__version__)

2.5.1+cu121


In [ ]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU : {torch.cuda.get_device_name(0)}")
else:
    print("GPU is not available. Using CPU.")


GPU is available!
Using GPU : Tesla T4


Creating Tensors

In [ ]:
#using empty
torch.empty(2,3)

tensor([[-1.0262e-22,  3.1543e-41, -1.0870e-22],
        [ 3.1543e-41,  0.0000e+00,  0.0000e+00]])

In [ ]:
#using zeros
torch.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
#using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
#using rand
torch.rand(2,3)

tensor([[0.9670, 0.2266, 0.3087],
        [0.7875, 0.1360, 0.7126]])

In [ ]:
#manual_seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
#using tensor
torch.tensor([1,2,3])


tensor([1, 2, 3])

In [ ]:
#other ways
#arange
print('using arange ->', torch.arange(1, 10, 2))
#linspace
print('using linspace ->', torch.linspace(1, 10, 5))
#logspace
print('using logspace ->', torch.logspace(1, 10, 5))
#eye [Identity Matrix]
print('using eye ->', torch.eye(3))
#full
print('using full ->',torch.full((3,3),5))

using arange -> tensor([1, 3, 5, 7, 9])
using linspace -> tensor([ 1.0000,  3.2500,  5.5000,  7.7500, 10.0000])
using logspace -> tensor([1.0000e+01, 1.7783e+03, 3.1623e+05, 5.6234e+07, 1.0000e+10])
using eye -> tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


Tensor Shapes

In [ ]:
x= torch.Tensor([[1,2,3],[4,5,6]])
x

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [ ]:
x.shape

torch.Size([2, 3])

In [ ]:
#to generate an empty tensor of same shape
torch.empty_like(x)

tensor([[ 2.9175e+13, -4.0288e-24, -2.5860e-35],
        [ 4.4910e-41, -2.3946e-35,  4.4910e-41]])

In [ ]:
#for generating a zero tensor of same shape
torch.zeros_like(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
torch.ones_like(x)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

Tensor Datatype

In [ ]:
#find data type
x.dtype

torch.float32

In [ ]:
#assign data type
torch.tensor([1.0,2.0,3.0],dtype = torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
torch.tensor([1,2,3], dtype = torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [ ]:
# using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [ ]:
torch.rand_like(x,dtype = torch.float32)

tensor([[0.2239, 0.3023, 0.1784],
        [0.8238, 0.5557, 0.9770]])

Mathematical Operations

1. Scaler Operation

In [ ]:
x = torch.rand(2,2)
x

tensor([[0.4440, 0.9478],
        [0.7445, 0.4892]])

In [ ]:
#addition
x+2
#substraction
x-1
#multiplication
x*5
#division
x/2
#int division
(x*100)//3
#mod
((x*100)//3)%2
#power
x**2

#ALL THE ABOVE OPERATIONS ARE PERFORMED ON ALL THE ELEMENTS OF THE TENSOR.

tensor([[0.1972, 0.8984],
        [0.5543, 0.2393]])

Element wise operations.

In [ ]:
a = torch.rand(2,3)
b= torch.rand(2,3)
print(a)
print(b)

tensor([[0.5163, 0.0359, 0.6476],
        [0.3430, 0.3182, 0.5261]])
tensor([[0.0447, 0.5123, 0.9051],
        [0.5989, 0.4450, 0.7278]])


In [ ]:
#add
a+b
#substraction
a-b
#multiplication
a*b
#division
a/b
#power
a**b
#mod
a//b

#ALL THESE OPERATIONS ARE PERFORMED ELEMENT WISE.

tensor([[11.,  0.,  0.],
        [ 0.,  0.,  0.]])

In [ ]:
c = torch.tensor([1,-2,3,-4])


In [ ]:
#abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [ ]:
#negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [ ]:
d = torch.tensor([1.9,2.3,3.7,4.4])

In [ ]:
#round
torch.round(d)

tensor([2., 2., 4., 4.])

In [ ]:
#ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [ ]:
#floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [ ]:
#clamp
torch.clamp(d,min= 2,max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

Reduction Operations

In [ ]:
#Here we reduce the tensor in a single number.

In [ ]:
e = torch.randint(size=(2,3),low=0,high=10)
f= torch.randint(size=(2,3),low =0,high=10, dtype=torch.float32)
f

tensor([[2., 9., 5.],
        [0., 4., 2.]])

In [ ]:
#sum
torch.sum(e)

tensor(21)

In [ ]:
#sum along columns
torch.sum(e, dim=0)

tensor([11,  1,  9])

In [ ]:
#sum along rows
torch.sum(e, dim=1)

tensor([12,  9])

In [ ]:
#mean of whole tensor
torch.mean(f)
torch.mean(f, dim=0)
torch.mean(f, dim=1)

tensor([3.3333, 4.0000])

In [ ]:
#median
torch.median(f)

tensor(4.)

In [ ]:
#max and min
torch.max(f)
torch.min(f)
torch.max(f, dim=0)
torch.min(f, dim=1)

torch.return_types.min(
values=tensor([0., 0.]),
indices=tensor([0, 0]))

In [ ]:
#product
torch.prod(f)
torch.prod(f, dim=0)
torch.prod(f, dim=1)

tensor([0., 0.])

In [ ]:
#standard devaition
torch.std(f)

tensor(3.2042)

In [ ]:
#vaiance
torch.var(f)

tensor(10.2667)

In [ ]:
#argmin
torch.argmin(f)

tensor(3)

In [ ]:
#argmax
torch.argmax(f)

tensor(1)

Matrix Operations

In [ ]:
f= torch.randint(size=(2,3),low=0,high=10)
g= torch.randint(size=(3,2),low=0,high=10)

print(f)
print(g)


tensor([[5, 2, 6],
        [9, 6, 8]])
tensor([[4, 0],
        [0, 2],
        [0, 2]])


In [ ]:
#matrix multiplication
torch.matmul(f,g)


tensor([[20, 16],
        [36, 28]])

In [ ]:
vector1= torch.tensor([1,2])
vector2= torch.tensor([3,4])

#dot product
torch.dot(vector1,vector2)

tensor(11)

In [ ]:
#transpose
torch.transpose(f,0,1)

tensor([[5, 9],
        [2, 6],
        [6, 8]])

In [ ]:
#determinant
h= torch.randint(size=(3,3), low =0,high=10, dtype=torch.float32)
torch.det(h)

tensor(-368.)

In [ ]:
#inverse
torch.inverse(h)

tensor([[-0.0217, -0.0489,  0.1467],
        [-0.0435,  0.1522,  0.0435],
        [ 0.1304,  0.0435, -0.1304]])

Comparision Operations

In [ ]:
i = torch.randint(size=(2,3),low=0,high=10)
j = torch.randint(size=(2,3),low=0,high=10)
print(i)
print(j)

tensor([[0, 8, 1],
        [3, 5, 1]])
tensor([[5, 4, 4],
        [6, 4, 4]])


In [ ]:
#greater
i>j
#smaller
i<j
#equal to
i==j
#not equal to
i!=j
#greater than equal to
i>=j
#less than equal to
i<=j

tensor([[ True, False,  True],
        [ True, False,  True]])

Specail Functions

In [ ]:
k = torch.randint(size=(2,3),low=0,high=10, dtype = torch.float32)
k

tensor([[1., 0., 1.],
        [3., 4., 2.]])

In [ ]:
#log
torch.log(k)

tensor([[1.3863,   -inf, 1.7918],
        [2.1972, 0.6931, 2.0794]])

In [ ]:
#exp
torch.exp(k)

tensor([[5.4598e+01, 1.0000e+00, 4.0343e+02],
        [8.1031e+03, 7.3891e+00, 2.9810e+03]])

In [ ]:
#sqrt
torch.sqrt(k)

tensor([[2.0000, 0.0000, 2.4495],
        [3.0000, 1.4142, 2.8284]])

In [ ]:
#sigmoid
torch.sigmoid(k)

tensor([[0.9820, 0.5000, 0.9975],
        [0.9999, 0.8808, 0.9997]])

In [ ]:
#softmax
torch.softmax(k, dim=0)

tensor([[0.1192, 0.0180, 0.2689],
        [0.8808, 0.9820, 0.7311]])

In [ ]:
#relu
torch.relu(k)

tensor([[1., 0., 1.],
        [3., 4., 2.]])

Implace Operations.

In [ ]:
m = torch.rand(2,3)
n = torch.rand(2,3)
print(m)
print(n)


tensor([[0.8889, 0.7065, 0.6206],
        [0.9865, 0.4436, 0.1944]])
tensor([[0.8794, 0.9382, 0.9398],
        [0.5705, 0.4333, 0.4431]])


In [ ]:
m.add_(n)

tensor([[1.7683, 1.6447, 1.5603],
        [1.5569, 0.8769, 0.6375]])

In [ ]:
m

tensor([[1.7683, 1.6447, 1.5603],
        [1.5569, 0.8769, 0.6375]])

In [ ]:
n

tensor([[0.8794, 0.9382, 0.9398],
        [0.5705, 0.4333, 0.4431]])

In [ ]:
m.relu_() #permanent inplce operation

tensor([[1.7683, 1.6447, 1.5603],
        [1.5569, 0.8769, 0.6375]])

Copying a Tensor.

In [ ]:
a = torch.rand(2,3)
a

tensor([[2.0153e-02, 1.2708e-04, 2.4937e-01],
        [5.6100e-01, 8.2438e-01, 9.6683e-01]])

In [ ]:
b=a

In [ ]:
b

tensor([[2.0153e-02, 1.2708e-04, 2.4937e-01],
        [5.6100e-01, 8.2438e-01, 9.6683e-01]])

In [ ]:
a[0][0]=0
a

tensor([[0.0000e+00, 1.2708e-04, 2.4937e-01],
        [5.6100e-01, 8.2438e-01, 9.6683e-01]])

In [ ]:
b

tensor([[0.0000e+00, 1.2708e-04, 2.4937e-01],
        [5.6100e-01, 8.2438e-01, 9.6683e-01]])

In [ ]:
id(a)

140555041579680

In [ ]:
id(b)

140555041579680

In [ ]:
#as same id of a and b
# so to copy a tensor , we can use clone

In [ ]:
b = a.clone()

In [ ]:
a



tensor([[0.0000e+00, 1.2708e-04, 2.4937e-01],
        [5.6100e-01, 8.2438e-01, 9.6683e-01]])

In [ ]:
a[0][0]=10

In [ ]:
a

tensor([[1.0000e+01, 1.2708e-04, 2.4937e-01],
        [5.6100e-01, 8.2438e-01, 9.6683e-01]])

In [ ]:
b

tensor([[0.0000e+00, 1.2708e-04, 2.4937e-01],
        [5.6100e-01, 8.2438e-01, 9.6683e-01]])

In [ ]:
id(a)

140555041579680

In [ ]:
id(b)

140555046449808

Tensors Operations on GPU

In [ ]:
torch.cuda.is_available()

True

In [ ]:
device = torch.device('cuda')

In [ ]:
#creating a new tensor on GPU
torch.rand((2,3), device=device)

tensor([[0.2026, 0.5129, 0.4331],
        [0.0106, 0.2267, 0.9168]], device='cuda:0')

In [ ]:
#moving an existing tensor to GPU
a = torch.rand(2,3)
a

tensor([[0.2445, 0.7377, 0.0658],
        [0.0227, 0.5597, 0.0407]])

In [ ]:
b = a.to(device) # moved to GPU

In [ ]:
b+5

tensor([[5.2445, 5.7377, 5.0658],
        [5.0227, 5.5597, 5.0407]], device='cuda:0')

In [ ]:
#Calculations in GPU is very fast.

Reshaping Tensors

In [ ]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
#reshape
a.reshape(2,8)

tensor([[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
#flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
b = torch.rand(2,3,4)
#permute helps to change the permutation.
b.permute(2,1,0).shape

torch.Size([4, 3, 2])

In [ ]:
#unsqueeze #to add new dimensions at any positions
#image size
c= torch.rand(226,226,3)
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [ ]:
#squeeze
d = torch.rand(1,20)
d.squeeze(0).shape

torch.Size([20])

Pytorch to Numpy and Numpy to Pytorch are interchangable.

In [ ]:
import numpy as np


In [ ]:
a= torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [ ]:
b = a.numpy()

In [ ]:
type(b)

numpy.ndarray

In [ ]:
c = np.array([1,2,3])
c

array([1, 2, 3])

In [ ]:
torch.from_numpy(c)

tensor([1, 2, 3])